// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CourierCore.Models
{
    public partial class TpLocations
    {
        public TpLocations()
        {
            TpUserLocationPresence = new HashSet<TpUserLocationPresence>();
        }

        public Guid LocId { get; set; }
        public Guid? LocDelId { get; set; }
        public string LocName { get; set; }
        public string LocDescription { get; set; }

        public virtual ICollection<TpUserLocationPresence> TpUserLocationPresence { get; set; }
    }
}