// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CourierCore.Models
{
    public partial class TpMenuVolumeTypes
    {
        public TpMenuVolumeTypes()
        {
            TpMenuItems = new HashSet<TpMenuItems>();
            TpOrderItems = new HashSet<TpOrderItems>();
            TpPreCheckItems = new HashSet<TpPreCheckItems>();
        }

        public Guid MvtpId { get; set; }
        public Guid? MvtpDelId { get; set; }
        public string MvtpName { get; set; }
        public string MvtpDescription { get; set; }
        public string MvtpTypeName { get; set; }
        public int? MvtpPrecision { get; set; }
        public string MvtpFormat { get; set; }

        public virtual ICollection<TpMenuItems> TpMenuItems { get; set; }
        public virtual ICollection<TpOrderItems> TpOrderItems { get; set; }
        public virtual ICollection<TpPreCheckItems> TpPreCheckItems { get; set; }
    }
}