// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CourierCore.Models
{
    public partial class TpPreCheckItems
    {
        public TpPreCheckItems()
        {
            InversePcitPcitIdMasterNavigation = new HashSet<TpPreCheckItems>();
        }

        public Guid PcitId { get; set; }
        public Guid PcitPrchId { get; set; }
        public Guid? PcitPcitIdMaster { get; set; }
        public Guid PcitSlgrId { get; set; }
        public Guid PcitMitmId { get; set; }
        public Guid? PcitMvtpId { get; set; }
        public decimal? PcitVolume { get; set; }
        public int PcitCount { get; set; }
        public decimal PcitPrice { get; set; }
        public decimal PcitPriceDiscount { get; set; }
        public decimal PcitPriceMargin { get; set; }
        public decimal PcitVat { get; set; }
        public decimal PcitPriceVat { get; set; }
        public bool PcitIsHidden { get; set; }
        public string PcitComment { get; set; }
        public string PcitMarkCode { get; set; }
        public int? PcitOrder { get; set; }

        public virtual TpMenuItems PcitMitm { get; set; }
        public virtual TpMenuVolumeTypes PcitMvtp { get; set; }
        public virtual TpPreCheckItems PcitPcitIdMasterNavigation { get; set; }
        public virtual TpPreChecks PcitPrch { get; set; }
        public virtual ICollection<TpPreCheckItems> InversePcitPcitIdMasterNavigation { get; set; }
    }
}