// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CourierCore.Models
{
    public partial class TpUsers
    {
        public TpUsers()
        {
            TpGuestDeliveries = new HashSet<TpGuestDeliveries>();
            TpGuests = new HashSet<TpGuests>();
            TpOrdersOrdrUsr = new HashSet<TpOrders>();
            TpOrdersOrdrUsrIdOperatorNavigation = new HashSet<TpOrders>();
            TpUserLocationPresenceUslpUsr = new HashSet<TpUserLocationPresence>();
            TpUserLocationPresenceUslpUsrIdBeginNavigation = new HashSet<TpUserLocationPresence>();
            TpUserLocationPresenceUslpUsrIdEndNavigation = new HashSet<TpUserLocationPresence>();
        }

        public Guid UsrId { get; set; }
        public Guid UsrUsrrId { get; set; }
        public Guid? UsrLggrId { get; set; }
        public Guid? UsrPeplId { get; set; }
        public Guid? UsrDelId { get; set; }
        public string UsrName { get; set; }
        public string UsrDescription { get; set; }
        public string UsrDocumentNameSignature { get; set; }
        public string UsrLogin { get; set; }
        public byte[] UsrPassword { get; set; }
        public string UsrQuickCode { get; set; }
        public bool UsrSimpleLogonEnabled { get; set; }
        public bool UsrIsDisabled { get; set; }
        public bool UsrIsPortalLogin { get; set; }

        public virtual TpPeople UsrPepl { get; set; }
        public virtual ICollection<TpGuestDeliveries> TpGuestDeliveries { get; set; }
        public virtual ICollection<TpGuests> TpGuests { get; set; }
        public virtual ICollection<TpOrders> TpOrdersOrdrUsr { get; set; }
        public virtual ICollection<TpOrders> TpOrdersOrdrUsrIdOperatorNavigation { get; set; }
        public virtual ICollection<TpUserLocationPresence> TpUserLocationPresenceUslpUsr { get; set; }
        public virtual ICollection<TpUserLocationPresence> TpUserLocationPresenceUslpUsrIdBeginNavigation { get; set; }
        public virtual ICollection<TpUserLocationPresence> TpUserLocationPresenceUslpUsrIdEndNavigation { get; set; }
    }
}