// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CourierCore.Models
{
    public partial class TpUserLocationPresence
    {
        public Guid UslpId { get; set; }
        public Guid UslpUsrId { get; set; }
        public Guid UslpLocId { get; set; }
        public Guid? UslpUsrIdBegin { get; set; }
        public Guid? UslpUsrIdEnd { get; set; }
        public DateTime UslpDateBegin { get; set; }
        public DateTime? UslpDateEnd { get; set; }

        public virtual TpLocations UslpLoc { get; set; }
        public virtual TpUsers UslpUsr { get; set; }
        public virtual TpUsers UslpUsrIdBeginNavigation { get; set; }
        public virtual TpUsers UslpUsrIdEndNavigation { get; set; }
    }
}